### ISSUE TITLE
looks like a bug in the getAddress function

### ISSUE THREAD

**Issue by yufeng-chen-tyson** [tross-tyson/mdata_go#13]
Thea, shouldn't it be Sha512HashValue(gtin)[`:`constants.FAMILY_VERB_ADDRESS_LENGTH] to make the address 64+6=70 bytes long?

https://github.com/tross-tyson/mdata_go/blob/c0c6341c7fad8c7741bd49898e3eaa445e146c04/src/mdata_client/client/mdata_client.go#L386

**Comment by txross** [comment]
@yufeng-chen-tyson EXCELLENT CATCH! I copied that code from intkey-go client, but didn't realize it was using a different addressing scheme than the xo-go processor... Fixed in next commit!
