### ISSUE TITLE
Iterate a byte slice, looks like a bug

### ISSUE THREAD

**Issue by yufeng-chen-tyson** [tross-tyson/mdata_go#14]
`products` is a byte slice, do you want to iterate a string slice instead?

https://github.com/tross-tyson/mdata_go/blob/c0c6341c7fad8c7741bd49898e3eaa445e146c04/src/mdata_client/commands/list/list.go#L66

**Comment by txross** [comment]
@yufeng-chen-tyson 
line 67 stringifies the product; it would be more efficient to range over a byte slice than a string slice, no?

**Comment by yufeng-chen-tyson** [comment]
if variable products is of type []byte, I believe variable product is going to hold a single byte in each iteration. So string(product) will yield a string of length of single byte, isn't it?

**Comment by yufeng-chen-tyson** [comment]
@tross-tyson see my comment above

**Comment by txross** [comment]
@yufeng-chen-tyson Ohhh you're totally right. I'll just make the List() return []string. Thanks for finding that!

Ideally these would become test cases, but putting testing aside so that maybe we can demo the processor. :S
