### ISSUE TITLE
UoM feels like way up for debate - how to simplify?

### ISSUE THREAD

**Issue by desktophero** [tross-tyson/mdata_go#4]
UoM ...  this feels like a way to spin and spiral without moving forward. 

I would love for our team to land on the first view of UoM as a construct so we can define/declare the next iteration.

My personal, first, UoM struct would be in the context of **weight** ...

**Comment by txross** [comment]
For Tyson, we measure product in terms of either Net Weight or Case Weight. In Tyson's ERP, UoM is one of ["Cases", "LBS"]. 

We can include standard weight and uom of that weight in the GTIN product spec... do you foresee it being used as a way to determine OS&Ds in the future if say a customer posts the total cases/total weight to the blockchain and the data is verified against standard product master?

**Comment by txross** [comment]
Whatever key:value pairs you want to set for a product, the mechanism is available. There are no more default attributes.
