### ISSUE TITLE
Bad info from me ... ? Transact verbs

### ISSUE THREAD

**Issue by desktophero** [tross-tyson/mdata_go#5]
for the master data (MD) transaction processor (TP), is my past question on "discontinue", not really valid anymore?!

The RFC spec includes this:
```
ProductDeactivate - Deactivate a product, setting its state to INACTIVE.
```

The value is called out as a `Transactions` registered value for CLIs based on this input. That might not mean the derived value is 100% this implementation but the evolution of the pattern is updates to make sure the pattern is applicable. For Deactivate, this might be covered by `Update` ... TBD

**Comment by txross** [comment]
Hahaha, well to be honest... I'm struggling to understand the value of "discontinue"... lacking retail and industry experience myself. Is the verbiage to "discontinue" a product standard in the industry? If so, let's always go with the ubiquitous language of the business/industry.

**Comment by txross** [comment]
Added set command; a user may set state to one of ACTIVE, INACTIVE, DISCONTINUED
