### ISSUE TITLE
Do we need ProductActivate  ?

### ISSUE THREAD

**Issue by madushankaf** [tross-tyson/mdata_go#7]
`ProductUpdate - Update (replace) the properties of a Product in the state.
ProductDeactivate - Deactivate a product, setting its state to INACTIVE.`

Isn't the  'ProductDeactivate' is similar to  'ProductUpdate'?
 If no, don't we need a 'ProductActivate'? 

ref: #5

**Comment by txross** [comment]
Good point, maybe we should change that to ProductSetState to one of [Active, Inactive].

**Comment by madushankaf** [comment]
Yeah

**Comment by txross** [comment]
Added states ACTIVE, INACTIVE, and DISCONTINUED to the "set" command
